#! /bin/sh

### BEGIN INIT INFO
# Provides:          rahunas
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Should-Start:      $local_fs $network
# Should-Stop:       $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Handles the rahunas daemon
# Description:       Starts, stops the rahunas daemon. 
### END INIT INFO

PATH=/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/rahunasd
NAME=rahunasd
DESC="rahunasd: Rahu Network Access Server"

# This value is overriden in /etc/default/rahunas if it exists
RUN_DAEMON=no

test -f $DAEMON || exit 0

set -e

# Get configuration
if [ -r /etc/default/rahunas ]; then
  . /etc/default/rahunas
fi

case "$1" in
  start)
	echo -n "Starting $DESC: "
	/etc/rahunas/firewall.sh
	if [ "$RUN_DAEMON" = "yes" ]; then
		start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
		--exec $DAEMON
		echo done
	else
		echo disabled 
	fi
	;;
  stop)
	echo -n "Stopping $DESC: "
	start-stop-daemon --stop --oknodo --quiet --pidfile /var/run/$NAME.pid \
		--exec $DAEMON
	echo done 
	;;
  restart|force-reload)
	echo -n "Restarting $DESC: "
	start-stop-daemon --stop --oknodo --quiet --pidfile \
		/var/run/$NAME.pid --exec $DAEMON
	sleep 1

	/etc/rahunas/firewall.sh
	start-stop-daemon --start --quiet --pidfile \
		/var/run/$NAME.pid --exec $DAEMON
	echo "$NAME."
	;;
  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start|stop|restart|force-reload}" >&2
	exit 1
	;;
esac

exit 0
